ALTER TABLE "usuario"
ADD COLUMN "streak_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "longest_streak" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "xp_points" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "level" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "last_active_day" DATE;
